
openframeworks:
  version: 0.9.3
  zip_name:
    darwin: of_v{0}_{1}_release.zip
    linux: of_v{0}_{1}_release.tar.gz

  release_url: http://openframeworks.cc/versions/v{0}/


  projectGenerator:
    osx: projectGenerator-osx/projectGenerator.app/Contents/Resources/app/app/projectGenerator
    linux64: apps/projectGenerator/commandLine/bin/projectGenerator

app:
  executable:
    darwin: bin/app.app/Contents/MacOS/app
    linux: bin/app

addons:
  ofxKinect: true

  ofxLoopin:
    git: https://github.com/koopero/ofxLoopin.git

  ofxJSON:
    git: https://github.com/jefftimesten/ofxJSON.git
